name: movie
description: "Movie App"

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  toggle_switch: ^2.3.0
  carousel_slider: ^5.1.1
  http: ^1.5.0
  flutter_bloc: ^9.1.1
  dio: ^5.4.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/
    - assets/splash/
    - assets/login/
    - assets/register/
    - assets/profile/
    - assets/onboarding/
    - assets/forget_password/
    - assets/bottom_navigation_bar/
    - assets/empty_search/empty.png

  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg
